### PR TITLE
Rearrange imports and remove unused imports

### PR DESCRIPTION
**Pull request by Warvito**
Rearrange imports and remove unused imports as proposed in  #19
Add also some blank lines between imports and functions and between functions following PEP8 recommendations

### CODE REVIEW

**Comment by Warvito** [comment]
Hi @robg-answer and @mehranrashid . I guess the CI system cannot verify my commits and PRs (I guess it is because I do not have the permissions to use it). When you have time, could you please check if this import rearrangement is okay?

**Comment by robg-answer** [comment]
See #24

**Comment by robg-answer** [comment]
The image were using should be public for the CI, when it's been made public (or moved somewhere where it can be) 
I'll push up a fix and merge to develop and you should be able to rebase

**Comment by robg-answer** [comment]
#24 Is now fixed, do a merge from develop and you should be good to go!

**Review by robg-answer — APPROVED** [review]

**Review by yorkeanswer — APPROVED** [review]
Thank you Walter 🎉

**Pull request merged**
